### ISSUE TITLE
dual <port> user error

### ISSUE THREAD

**Issue by schell** [fgaz/dual#1]
After installing with `stack install dual-game` and running, I get this error:
```
schell~$ dual 8888
dual: user error (unknown GLUT entry glutInit)
```
I'm on Ubuntu 17.10.

**Comment by fgaz** [comment]
Tomorrow I'll set up an ubuntu vm and check.

Sanity check: is the freeglut package from ubuntu's repos installed?

**Comment by fgaz** [comment]
Yup, I tried it on a clean system and the only additional step I had to do was installing `freeglut3-dev`. I'll add it to the readme.

Please close the issue if this solves it for you.

**Comment by schell** [comment]
Marvelous! Thank you.
